# Generated by Django 2.2.12 on 2020-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coverImage',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
