# Generated by Django 2.2.12 on 2020-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='coverImage',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
    ]
