# Generated by Django 2.2.12 on 2020-07-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200630_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='cv',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
