# Generated by Django 2.2.12 on 2020-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200701_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='EdQual',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='WorkExp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='interests',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='references',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='skillsExp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
