# Generated by Django 2.2.12 on 2020-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200713_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='EdQual',
        ),
    ]
